# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

parameters:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'



jobs:
  - job: Build
    displayName: Build
   # pool:
   #   vmImage: ${{parameters.vmImage}}

    variables:
      solution: '$(Agent.BuildDirectory)/s/ASP.net-MVC-SampleApp/**/*.sln'
    steps:

    - checkout: self
      displayName: 'Asp.net app'

    - checkout: ArmTemplateAppservice
      displayName: 'arm template'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '${{ parameters.buildPlatform }}'
        configuration: '${{ parameters.buildConfiguration }}'

    - task: VSTest@2
      inputs:
        platform: '${{ parameters.buildPlatform }}'
        configuration: '${{ parameters.buildConfiguration }}'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop-$(Build.BuildId)'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Agent.BuildDirectory)/s/ArmTemplateAppservice/Appservice-Arm-Templates/'
        ArtifactName: 'drop-arm'
        publishLocation: 'Container'


