

parameters:
- name: environment
  default: ''
  type: string
- name: resourceGroupName
  default: ''
  type: string
- name: location
  default: ''
  type: string
- name: AppserviceName
  default: '' 
  type: string
- name: AppserviceplanName
  default: '' 
  type: string


jobs:
  -  deployment:  deploy
     displayName: deploy App
    # pool:
    #   vmImage: ${{ parameters.vmImage }}
     environment: ${{ parameters.environment }}
     strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop-$(Build.BuildId)'
                downloadPath: '$(System.DefaultWorkingDirectory)'
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop-arm'
                downloadPath: '$(System.DefaultWorkingDirectory)'
            
            - task: AzurePowerShell@5
              inputs:
                azureSubscription: 'devops team service connection'
                ScriptType: 'FilePath'
                ScriptPath: '$(System.DefaultWorkingDirectory)/drop-arm/AzureResourceGroup-Automation.ps1'
                ScriptArguments: '-resourceGroupName  ${{ parameters.resourceGroupName }} -location ${{ parameters.location }}'
                azurePowerShellVersion: 'LatestVersion'

            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'devops team service connection'
                subscriptionId: '23d9e783-b881-49e7-b2f1-a1a6f1bc2d90'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '${{ parameters.resourceGroupName}}'
                location: '${{ parameters.location }}'
                templateLocation: 'Linked artifact'
                csmFile: '$(System.DefaultWorkingDirectory)/drop-arm/TestArm.json'
                csmParametersFile: '$(System.DefaultWorkingDirectory)/drop-arm/TestArm.parameters.json'
                overrideParameters: '-AppserviceName ${{ parameters.AppserviceName }} -AppserviceplanName ${{ parameters.AppserviceplanName }}'
                deploymentMode: 'Incremental'

            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'devops team service connection'
                appType: 'webApp'
                WebAppName: $(AppserviceName)
                packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
